In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk

/home/joaogarcia/Documents/DataScience/venv/lib/python3.6/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

# TODO

## 3- Análise de Sentimento
    3.1 - Análise de Sentimento para cada comentário, e avaliar se o comentário é positivo ou negativo.
    3.2 - Criar uma Coluna para cada linha ter o resultado sentimento do c
    3.3 - Analisar e criar vizualizações para esses resultados

## 1- Limpar e arrumar conjunto de texto
    
    2.2 - Limpar o Texto. Pontuações, tudo em letra minúscula, stopwords, etc.
    2.3 - Tokenizar todos o texto
    2.4 - Gerar tabelas de contagem de palavras por:
        2.4.1 - Websites
        2.4.2 - Brands
        2.4.3 - Modelo

In [2]:
data = pd.read_csv('./Dataset/NLP_Data.csv')

In [3]:
comments = data[['Website','Brand', 'Comment#1', 'Comment#2']]
comments.head(2)

,Website,Brand,Comment#1,Comment#2
0,lowes,General Electric,Functional,Pros: fingerprint resistant so you don't have ...
1,lowes,Frigidaire,Ample Door Storage User Friendly Visibility,Feels solid and “upscale”. Excellent design of...

### 1.1 - Limpando Valores Nulos

In [4]:
comments.fillna('', inplace=True)
comments.isnull().sum()

/home/joaogarcia/Documents/DataScience/venv/lib/python3.6/site-packages/pandas/core/frame.py:3790: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

Website      0
Brand        0
Comment#1    0
Comment#2    0
dtype: int64

### 1.2 - Juntar os dois tipos de comentário em um só

In [6]:
corpus =  comments.copy()

col_names = ['Comment#1', 'Comment#2']
corpus['Full_Comment'] = corpus.apply(lambda x: x[col_names[0]] + ' ' + x[col_names[1]], axis=1)
corpus.head(5)

,Website,Brand,Comment#1,Comment#2,Full_Comment
0,lowes,General Electric,Functional,Pros: fingerprint resistant so you don't have ...,Functional Pros: fingerprint resistant so you ...
1,lowes,Frigidaire,Ample Door Storage User Friendly Visibility,Feels solid and “upscale”. Excellent design of...,Ample Door Storage User Friendly Visibility Fe...
2,bestbuy_us,Whirlpool,So much room,I love this fridge. So much room over having a...,So much room I love this fridge. So much room ...
3,bestbuy_us,Whirlpool,So much room,I love this fridge. So much room over having a...,So much room I love this fridge. So much room ...
4,bestbuy_us,Whirlpool,So much room,I love this fridge. So much room over having a...,So much room I love this fridge. So much room ...

### 1.3 - Limpar o Texto. Pontuações, tudo em letra minúscula, stopwords, etc.

In [7]:
import re
import string
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
def clean_text(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [9]:
col_name = ['Full_Comment']
corpus['Full_Comment'] = corpus.apply(lambda x: clean_text(x[col_name[0]]), axis=1 )
corpus['Full_Comment'][0]

'functional pros fingerprint resistant so you dont have to constantly wipe it down drawers are good size and are plentiful water dispenser works great cons its noisy when making ice to the point you think one thing is wrong with it'

In [10]:
count_vector = CountVectorizer(stop_words='english')
words_count_data = count_vector.fit_transform(corpus.Full_Comment)
document_term_matrix = pd.DataFrame(words_count_data.toarray(), columns=count_vector.get_feature_names())
document_term_matrix.index = corpus.index
document_term_matrix.head()

,aaa,aahs,abd,abilities,ability,able,ablity,abnormal,abnormally,abound,...,yup,zero,zipper,zombie,zone,zones,zonked,ótima,ótimo,ótimogela
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
document_term_matrix.shape

(20473, 9561)

Tenho muitos valores. Tenho que de alguma forma melhorar isso, porque senão vai ser bem dificil trabalhar com uma tabela tão grande.

Algumas ideias:
- Agrupar por Site, e diminuir o numero de Linhas
- Stemming/Lemmanization (tenho palavras bem parecida como abilities, ability, ablity)
- Vejo que tenho palavras em portugues (ótimo, ótima) -> Posso juntar as stop words das duas linguas talvez

### 1.3.1 - Agrupando por site, e pegando o site com mais linhas que é o lowes

In [12]:
lowes_comments = corpus.copy()
lowes_comments = lowes_comments.loc[lowes_comments['Website'] == 'lowes']
lowes_comments.reset_index(inplace=True)
lowes_comments.head()

,index,Website,Brand,Comment#1,Comment#2,Full_Comment
0,0,lowes,General Electric,Functional,Pros: fingerprint resistant so you don't have ...,functional pros fingerprint resistant so you d...
1,1,lowes,Frigidaire,Ample Door Storage User Friendly Visibility,Feels solid and “upscale”. Excellent design of...,ample door storage user friendly visibility fe...
2,6,lowes,Frigidaire,My refrigerator stopped working in less than a...,We were away from the weekend and the frig wen...,my refrigerator stopped working in less than a...
3,7,lowes,Frigidaire,My refrigerator stopped working in less than a...,We were away from the weekend and the frig wen...,my refrigerator stopped working in less than a...
4,11,lowes,Whirlpool,Good Product,We bought this product for our office and they...,good product we bought this product for our of...

In [13]:
count_vector = CountVectorizer(stop_words='english')
words_count_data = count_vector.fit_transform(lowes_comments.Full_Comment)
lowes_dtm = pd.DataFrame(words_count_data.toarray(), columns=count_vector.get_feature_names())
lowes_dtm.index = lowes_comments.index
lowes_dtm.head()

,aaa,aahs,abd,ability,able,ablity,abnormal,abnormally,abound,abrasive,...,young,younger,youre,youtube,yr,yrs,zero,zipper,zone,zones
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
lowes_dtm.sum().sort_values(ascending=False).head(30)

fridge          6987
love            5170
refrigerator    4796
great           4645
ice             4563
freezer         3683
door            3490
space           3247
water           2384
bought          2342
like            2228
room            1974
good            1938
maker           1845
new             1830
features        1526
nice            1516
just            1405
ago             1404
old             1303
shelves         1282
size            1254
inside          1223
happy           1101
far             1094
month           1094
drawer          1035
really          1034
doors           1019
perfect          981
dtype: int64

### 1.3.2 - SnowBallStemming

In [15]:
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer

In [16]:
def text_stem(text, stemmer):
    word_list = word_tokenize(text)
    text = [stemmer.stem(word) for word in word_list]
    text = ' '.join(text)
    return text

In [17]:
snowball_corpus = lowes_comments.copy()
snowBallStemmer = SnowballStemmer("english")
col_name = ['Full_Comment']
snowball_corpus['Full_Comment'] = snowball_corpus.apply(lambda x: text_stem(x[col_name[0]], snowBallStemmer), axis=1 )
snowball_corpus['Full_Comment'].head()

0    function pros fingerprint resist so you dont h...
1    ampl door storag user friend visibl feel solid...
2    my refriger stop work in less than a mon we we...
3    my refriger stop work in less than a mon we we...
4    good product we bought this product for our of...
Name: Full_Comment, dtype: object

In [18]:
count_vector = CountVectorizer(stop_words='english')
words_stem_count_data = count_vector.fit_transform(snowball_corpus.Full_Comment)
dtm_stem = pd.DataFrame(words_stem_count_data.toarray(), columns=count_vector.get_feature_names())
dtm_stem.index = snowball_corpus.index
dtm_stem.head()

,aaa,aah,ab,abd,abil,abl,abliti,abnorm,abound,abov,...,youl,youll,young,younger,youtub,yr,yrs,zero,zipper,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
dtm_stem.shape

(9518, 4280)

In [18]:
dtm_stem.sum().sort_values(ascending=False).head(30)

fridg       7110
love        5418
refriger    5004
great       4671
ice         4593
door        4509
freezer     3702
space       3327
veri        2977
water       2385
like        2343
bought      2342
look        2087
featur      1994
room        1977
good        1963
maker       1909
new         1830
work        1794
onli        1738
month       1725
drawer      1673
lot         1624
nice        1574
shelv       1523
need        1414
just        1405
ago         1404
size        1339
purchas     1320
dtype: int64

### 1.3.2 - PorterStemming

In [19]:
from nltk.stem import PorterStemmer

In [20]:
porter_corpus = lowes_comments.copy()
porterStemmer = PorterStemmer()
col_name = ['Full_Comment']
porter_corpus['Full_Comment'] = porter_corpus.apply(lambda x: text_stem(x[col_name[0]], porterStemmer), axis=1 )
porter_corpus['Full_Comment'].head()

0    function pro fingerprint resist so you dont ha...
1    ampl door storag user friendli visibl feel sol...
2    my refriger stop work in less than a mon we we...
3    my refriger stop work in less than a mon we we...
4    good product we bought thi product for our off...
Name: Full_Comment, dtype: object

In [22]:
count_vector = CountVectorizer(stop_words='english')
words_stem_count_data = count_vector.fit_transform(porter_corpus.Full_Comment)
dtm_stem_porter = pd.DataFrame(words_stem_count_data.toarray(), columns=count_vector.get_feature_names())
dtm_stem_porter.index = snowball_corpus.index
dtm_stem_porter.head()

,aaa,aah,ab,abd,abil,abl,abliti,abnorm,abound,abov,...,youer,youl,youll,young,younger,youtub,yr,zero,zipper,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
dtm_stem_porter.sum().sort_values(ascending=False).head(30)

thi         7927
fridg       7110
love        5418
refriger    5004
great       4645
ice         4593
door        4509
freezer     3702
space       3327
veri        2977
wa          2715
water       2385
like        2343
bought      2342
ha          2214
look        2087
featur      1994
room        1977
good        1963
maker       1909
new         1830
work        1794
onli        1738
month       1725
drawer      1673
lot         1624
nice        1574
shelv       1523
need        1414
just        1405
dtype: int64

Não Gostei dessa Porter Stemming, e apesar de ter ficado menor, o SnowBall nao me agradou muito também.

Vou continuar com a ideia de só pegar os comentários da Lowes e fazer sem stemming mesmo.

### 1.4 - Bigramas

In [31]:
from nltk.util import bigrams, trigrams

In [ ]:
def text_stem(text, stemmer):
    word_list = word_tokenize(text)
    text = [stemmer.stem(word) for word in word_list]
    text = ' '.join(text)
    return text

In [ ]:
lowes_comments